version: '3.8'
services: 
    db:
        image: mysql:8.0
        restart: always
        environment: 
            MYSQL_DATABASE: kanban
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            # PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        restart: always
        # tty: true
        # command: /bin/bash -c  'php artisan migrate; php artisan serve --host=0.0.0.0;'
        command: 'php artisan serve --host=0.0.0.0'
        # command: 'php artisan migrate'
        # volumes:
        #     - .:/app
        ports:
            - 8000:8000